openapi: 3.0.0
info:
    title: 'Mattchpoint'
    description: 'API to expose Mattchpoint Repository Access'
    version: '1.0.0'

servers:
    - url: '{host}/mattchpoint-{environment}/v1'
      description: 'API server for different environments'
      variables:
          url:
              default: 'https://localhost:3000'
              enum:
                  - 'https://a.com' 
                  - 'https://b.com'
              description: 'The base URL for the API server'

          environment:
              default: 'qa'
              enum:
                  - 'dev'
                  - 'qa'
                  - 'prod'
                  - 'test'
              description: 'The environment for the API server'

paths:
    /ping:
        get:
            tags:
                - mics
            summary: Pong
            description: Returns "pong" to confirm service is alive.
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: string
                                example: pong
    /healthcheck:
        get:
            tags:
                - mics
            summary: Returns the service health status.
            responses:
                200:
                    description: Health status response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: up