stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IMAGE: your-registry/your-image:latest

build:
  stage: build
  image: docker:23.0.2-alpine3.17
  tags:
    - techtransform
  services:
    - name: docker:23.0.2-dind-alpine3.17
      alias: docker
      command: ["--privileged", "--host=tcp://0.0.0.0:2375"]
  before_script:
    - docker --version
    - until docker info; do sleep 1; done
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main
