apiVersion: apps/v1
kind: Deployment
metadata:
  name: cci-web-deployment
  labels:
    app: cci-web
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: cci-web
  template:
    metadata:
      labels:
        app: cci-web
    spec:
      containers:
      - name: cci-web-container
        image: 533267147118.dkr.ecr.us-east-1.amazonaws.com/cci-web:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
          - name: SOME_ENV_VARIABLE
            value: "some_value"
