apiVersion: v1
kind: Service
metadata:
  name: cci-test-service
spec:
  type: NodePort  # Exposes the service externally using a load balancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-node
