#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#To find node when local machine using nvm and running a GUI for Git
  PATH="/usr/local/bin:$PATH"

  if [ -f $HOME/.nvm/nvm.sh ]
  then
    . $HOME/.nvm/nvm.sh
    PATH="$HOME/.nvm/versions/node/$(nvm current)/bin:$PATH"
  fi

npm run pre-commit